<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes, maximum-scale=3.0">
    <meta name="theme-color" content="<?php echo $theme ?? '#007bff'; ?>">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-status-bar-style" content="default">
    
    <!-- iOS Meta Tags -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta name="apple-mobile-web-app-title" content="Property Report">
    
    <title><?php echo htmlspecialchars($property->PropertyProfile->SiteAddress ?? 'Property Report'); ?> - Modern Agent</title>
    
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="<?php echo base_url('assets/reports/mobile/css/mobile.css'); ?>">
    
    <!-- JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>
    
    <!-- PWA Manifest -->
    <link rel="manifest" href="<?php echo base_url('assets/reports/mobile/manifest.json'); ?>">
    
    <!-- Dynamic Theme Styling -->
    <style>
        :root {
            --theme-color: <?php echo $theme ?? '#007bff'; ?>;
            --theme-color-light: <?php echo ($theme ?? '#007bff') . '20'; ?>;
            --theme-color-dark: <?php echo ($theme ?? '#007bff') . 'dd'; ?>;
        }
    </style>
    
    <!-- Structured Data for SEO -->
    <script type="application/ld+json">
    {
        "@context": "https://schema.org",
        "@type": "Report",
        "name": "Property Report for <?php echo htmlspecialchars($property->PropertyProfile->SiteAddress ?? ''); ?>",
        "description": "Comprehensive property analysis report generated by Modern Agent",
        "dateCreated": "<?php echo date('c'); ?>",
        "author": {
            "@type": "Organization",
            "name": "Modern Agent"
        }
    }
    </script>
</head>
<body>
    <!-- Loading Screen -->
    <div id="loading-screen" class="loading-screen">
        <div class="spinner-border text-light" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
        <p class="mt-3">Loading Property Report...</p>
        <div class="progress mt-2" style="width: 200px;">
            <div class="progress-bar progress-bar-striped progress-bar-animated" id="loading-progress" 
                 role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
    
    <!-- Mobile Report Container -->
    <div id="mobile-report" class="mobile-report" style="display: none;">
        
        <!-- Header Section -->
        <?php $this->load->view('reports/mobile/components/header', compact('property', 'user', 'theme')); ?>
        
        <!-- Navigation Tabs -->
        <?php $this->load->view('reports/mobile/components/navigation'); ?>
        
        <!-- Content Sections -->
        <div class="report-content">
            
            <!-- Property Overview -->
            <section id="overview" class="content-section active" data-section="overview">
                <?php $this->load->view('reports/mobile/components/property_overview', compact('property', 'mapUrl', 'propertyImages')); ?>
            </section>
            
            <!-- Comparable Sales -->
            <section id="comparables" class="content-section" data-section="comparables">
                <?php $this->load->view('reports/mobile/components/comparable_sales', compact('areaSalesAnalysis', 'property')); ?>
            </section>
            
            <!-- Market Analysis -->
            <section id="market" class="content-section" data-section="market">
                <?php $this->load->view('reports/mobile/components/market_analysis', compact('marketData', 'trends')); ?>
            </section>
            
            <!-- Neighborhood Info -->
            <section id="neighborhood" class="content-section" data-section="neighborhood">
                <?php $this->load->view('reports/mobile/components/neighborhood_info', compact('demographicData', 'schoolData', 'amenities')); ?>
            </section>
            
            <!-- AI Insights -->
            <section id="insights" class="content-section" data-section="insights">
                <?php $this->load->view('reports/mobile/components/ai_insights', compact('aiAnalysis', 'marketInsights')); ?>
            </section>
            
        </div>
        
        <!-- Footer -->
        <?php $this->load->view('reports/mobile/components/footer', compact('user', 'reportData')); ?>
        
        <!-- Share Modal -->
        <?php $this->load->view('reports/mobile/components/share_modal'); ?>
        
        <!-- Swipe Indicator -->
        <div class="swipe-indicator d-md-none">
            <i class="fas fa-chevron-left"></i>
            <span>Swipe to navigate</span>
            <i class="fas fa-chevron-right"></i>
        </div>
        
    </div>
    
    <!-- Error Display -->
    <div id="error-container" class="error-container" style="display: none;">
        <div class="error-content">
            <i class="fas fa-exclamation-triangle"></i>
            <h3>Report Loading Error</h3>
            <p id="error-message">There was an issue loading the report. Please try again.</p>
            <button class="btn btn-primary" onclick="location.reload()">
                <i class="fas fa-refresh"></i> Retry
            </button>
        </div>
    </div>
    
    <!-- JavaScript Configuration -->
    <script>
        // Global configuration for mobile report
        window.MobileReportConfig = {
            baseUrl: '<?php echo base_url(); ?>',
            reportId: <?php echo $reportData['project_id'] ?? 'null'; ?>,
            theme: '<?php echo $theme ?? '#007bff'; ?>',
            enableAnalytics: true,
            enableOffline: <?php echo $pwaEnabled ? 'true' : 'false'; ?>,
            chartOptions: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        position: 'bottom'
                    },
                    tooltip: {
                        mode: 'index',
                        intersect: false
                    }
                },
                interaction: {
                    mode: 'nearest',
                    axis: 'x',
                    intersect: false
                }
            }
        };
        
        // Property data for charts
        window.PropertyData = {
            property: <?php echo json_encode($property ?? new stdClass()); ?>,
            comparables: <?php echo json_encode($areaSalesAnalysis['comparable'] ?? []); ?>,
            marketData: <?php echo json_encode($marketData ?? []); ?>,
            demographics: <?php echo json_encode($demographicData ?? []); ?>
        };
    </script>
    
    <!-- Core JavaScript -->
    <script src="<?php echo base_url('assets/reports/mobile/js/mobile-report.js'); ?>"></script>
    <script src="<?php echo base_url('assets/reports/mobile/js/chart-interactions.js'); ?>"></script>
    
    <!-- Service Worker for PWA -->
    <script>
        if ('serviceWorker' in navigator && window.MobileReportConfig.enableOffline) {
            navigator.serviceWorker.register('<?php echo base_url('assets/reports/mobile/sw.js'); ?>')
                .then(function(registration) {
                    console.log('SW registered: ', registration);
                })
                .catch(function(registrationError) {
                    console.log('SW registration failed: ', registrationError);
                });
        }
    </script>
    
    <!-- Analytics -->
    <?php if (isset($analyticsEnabled) && $analyticsEnabled): ?>
    <script>
        // Google Analytics or custom analytics
        // Track mobile report views and interactions
        function trackEvent(category, action, label) {
            if (typeof gtag !== 'undefined') {
                gtag('event', action, {
                    'event_category': category,
                    'event_label': label
                });
            }
        }
        
        // Track report view
        trackEvent('Mobile Report', 'view', '<?php echo $property->PropertyProfile->SiteAddress ?? 'Unknown Property'; ?>');
    </script>
    <?php endif; ?>
    
    <!-- Error Handling -->
    <script>
        window.addEventListener('error', function(e) {
            console.error('Mobile report error:', e.error);
            document.getElementById('loading-screen').style.display = 'none';
            document.getElementById('mobile-report').style.display = 'none';
            document.getElementById('error-container').style.display = 'flex';
            document.getElementById('error-message').textContent = 'An unexpected error occurred: ' + e.message;
        });
        
        window.addEventListener('unhandledrejection', function(e) {
            console.error('Mobile report promise rejection:', e.reason);
            // Handle promise rejections gracefully
        });
    </script>
    
    <!-- Print Styles -->
    <style media="print">
        .loading-screen,
        .swipe-indicator,
        .nav-tabs,
        .footer,
        .share-modal {
            display: none !important;
        }
        
        .content-section {
            display: block !important;
            page-break-inside: avoid;
        }
        
        .chart-container {
            page-break-inside: avoid;
        }
        
        body {
            font-size: 12px;
        }
        
        .mobile-report {
            max-width: none !important;
        }
    </style>
</body>
</html> 