CREATE TABLE `lp_user_report_content` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `user_id` int(11) NOT NULL,
 `report_type` enum('buyer','seller') NOT NULL,
 `page_id` int(11) NOT NULL,
 `page_title` varchar(250) NOT NULL,
 `page_path` varchar(250) NOT NULL,
 `data` text NOT NULL,
 `created_at` datetime NOT NULL,
 `updated_at` datetime NOT NULL,
 `updated_by` int(11) NOT NULL,
 PRIMARY KEY (`id`),
 KEY `user_id` (`user_id`),
 KEY `report_type` (`report_type`),
 KEY `page_id` (`page_id`),
 KEY `created_at` (`created_at`),
 KEY `updated_at` (`updated_at`),
 KEY `updated_by` (`updated_by`)
) ENGINE=InnoDB COMMENT='Table contain customized data of report pages';


insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('1','0','seller','english','9','HOME BUYING PROCESS','user/preview/seller/english/9','{\"title\":{\"value\":\"HOME BUYING PROCESS\",\"limit\":45,\"type\":\"text\"},\"sub_title\":{\"value\":\"PAYMENT & FINANCING OPTIONS\",\"limit\":85,\"type\":\"text\"},\"point_1_title\":{\"value\":\"HOW BUYERS FIND HOME\",\"limit\":45,\"type\":\"text\"},\"point_1_sub_title\":{\"value\":\"Lets look at how buyers find a home\",\"limit\":85,\"type\":\"text\"},\"point_2_title\":{\"value\":\"PRICING CORRECTLY\",\"limit\":45,\"type\":\"text\"},\"point_2_sub_title\":{\"value\":\"What you should consider\",\"limit\":85,\"type\":\"text\"},\"point_3_title\":{\"value\":\"AVERAGE DAYS ON MARKET MARKET MARKET\",\"limit\":45,\"type\":\"text\"},\"point_3_sub_title\":{\"value\":\"Time it takes to sell a home\",\"limit\":85,\"type\":\"text\"},\"point_4_title\":{\"value\":\"MARKETING PLAN\",\"limit\":45,\"type\":\"text\"},\"point_4_sub_title\":{\"value\":\"Our plan to get your home sold quickly\",\"limit\":85,\"type\":\"text\"},\"point_5_title\":{\"value\":\"ANALYZE & OPTIMIZE SALES PRICE\",\"limit\":45,\"type\":\"text\"},\"point_5_sub_title\":{\"value\":\"Analyze and optimize our marketing efforts\",\"limit\":85,\"type\":\"text\"},\"point_6_title\":{\"value\":\"NEGOTIATING OFFERS\",\"limit\":45,\"type\":\"text\"},\"point_6_sub_title\":{\"value\":\"Negotiating the best offer for you\",\"limit\":85,\"type\":\"text\"},\"point_7_title\":{\"value\":\"TRANSACTION ROAD-MAP\",\"limit\":45,\"type\":\"text\"},\"point_7_sub_title\":{\"value\":\"Transaction road-map to help guide you\",\"limit\":85,\"type\":\"text\"}}','2019-08-06 11:08:20','2019-08-06 11:08:25','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('2','0','seller','english','10','HOW BUYERS FIND A HOME','user/preview/seller/english/10','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('3','0','seller','english','11','PRICING CORRECTLY','user/preview/seller/english/11','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('4','0','seller','english','12','AVERAGE DAYS ON MARKET','user/preview/seller/english/12','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('5','0','seller','english','13','PICS & ONLINE EXPOSURE','user/preview/seller/english/13','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('6','0','seller','english','14','PRINTED COLLATERAL','user/preview/seller/english/14','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('7','0','seller','english','15','SOCIAL MEDIA & NETWORKING','user/preview/seller/english/15','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('8','0','seller','english','16','ANALYZE & OPTIMIZE','user/preview/seller/english/16','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('9','0','seller','english','17','NEGOTIATING OFFERS','user/preview/seller/english/17','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('10','0','seller','english','18','TYPICAL TRANSACTION','user/preview/seller/english/18','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('11','0','seller','english','19','A PROMISE TO MY CLIENTS','user/preview/seller/english/19','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('12','0','seller','spanish','9','HOME BUYING PROCESS','user/preview/seller/spanish/9','{\"title\":{\"value\":\"HOME BUYING PROCESS\",\"limit\":45,\"type\":\"text\"},\"sub_title\":{\"value\":\"PAYMENT & FINANCING OPTIONS\",\"limit\":85,\"type\":\"text\"},\"point_1_title\":{\"value\":\"HOW BUYERS FIND HOME\",\"limit\":45,\"type\":\"text\"},\"point_1_sub_title\":{\"value\":\"Lets look at how buyers find a home\",\"limit\":85,\"type\":\"text\"},\"point_2_title\":{\"value\":\"PRICING CORRECTLY\",\"limit\":45,\"type\":\"text\"},\"point_2_sub_title\":{\"value\":\"What you should consider\",\"limit\":85,\"type\":\"text\"},\"point_3_title\":{\"value\":\"AVERAGE DAYS ON MARKET MARKET MARKET\",\"limit\":45,\"type\":\"text\"},\"point_3_sub_title\":{\"value\":\"Time it takes to sell a home\",\"limit\":85,\"type\":\"text\"},\"point_4_title\":{\"value\":\"MARKETING PLAN\",\"limit\":45,\"type\":\"text\"},\"point_4_sub_title\":{\"value\":\"Our plan to get your home sold quickly\",\"limit\":85,\"type\":\"text\"},\"point_5_title\":{\"value\":\"ANALYZE & OPTIMIZE SALES PRICE\",\"limit\":45,\"type\":\"text\"},\"point_5_sub_title\":{\"value\":\"Analyze and optimize our marketing efforts\",\"limit\":85,\"type\":\"text\"},\"point_6_title\":{\"value\":\"NEGOTIATING OFFERS\",\"limit\":45,\"type\":\"text\"},\"point_6_sub_title\":{\"value\":\"Negotiating the best offer for you\",\"limit\":85,\"type\":\"text\"},\"point_7_title\":{\"value\":\"TRANSACTION ROAD-MAP\",\"limit\":45,\"type\":\"text\"},\"point_7_sub_title\":{\"value\":\"Transaction road-map to help guide you\",\"limit\":85,\"type\":\"text\"}}','2019-08-06 11:08:20','2019-08-06 11:08:25','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('13','0','seller','spanish','10','HOW BUYERS FIND A HOME','user/preview/seller/spanish/10','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('14','0','seller','spanish','11','PRICING CORRECTLY','user/preview/seller/spanish/11','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('15','0','seller','spanish','12','AVERAGE DAYS ON MARKET','user/preview/seller/spanish/12','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('16','0','seller','spanish','13','PICS & ONLINE EXPOSURE','user/preview/seller/spanish/13','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('17','0','seller','spanish','14','PRINTED COLLATERAL','user/preview/seller/spanish/14','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('18','0','seller','spanish','15','SOCIAL MEDIA & NETWORKING','user/preview/seller/spanish/15','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('19','0','seller','spanish','16','ANALYZE & OPTIMIZE','user/preview/seller/spanish/16','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('20','0','seller','spanish','17','NEGOTIATING OFFERS','user/preview/seller/spanish/17','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('21','0','seller','spanish','18','TYPICAL TRANSACTION','user/preview/seller/spanish/18','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');
insert into `lp_user_report_content` (`id`, `user_id`, `report_type`, `language`, `page_no`, `page_title`, `page_path`, `data`, `created_at`, `updated_at`, `updated_by`) values('22','0','seller','spanish','19','A PROMISE TO MY CLIENTS','user/preview/seller/spanish/19','[]','2019-08-06 11:10:11','2019-08-06 11:10:17','70');