# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
  branches:
     production:
          - step:
               script:
                   - pipe: atlassian/ssh-run:0.3.0
                     variables:
                        SSH_USER: $MA_SSH_USER
                        SERVER: $MA_HOST
                        PORT: $MA_PORT
                        MODE: 'command'
                        COMMAND: $MA_PROD_SH