<?php
/**
 * AI Insights Component
 * 
 * Displays AI-generated market analysis and insights
 * with expandable sections and interactive elements
 */

// Get AI insights data
$ai_content = isset($ai_summary) ? $ai_summary : '';
$property_address = isset($property->PropertyProfile->SiteAddress) ? $property->PropertyProfile->SiteAddress : 'this property';
?>

<div class="ai-insights">
    
    <!-- AI Header -->
    <div class="ai-header">
        <div class="ai-icon">
            <i class="fas fa-brain"></i>
        </div>
        <div class="ai-title-section">
            <h2 class="ai-title">AI Market Analysis</h2>
            <p class="ai-subtitle">Powered by advanced AI to provide data-driven insights</p>
        </div>
        <div class="ai-badge">
            <i class="fas fa-robot"></i>
            GPT-4
        </div>
    </div>
    
    <!-- AI Content -->
    <div class="ai-content">
        <?php if (!empty($ai_content)): ?>
            <?php echo $ai_content; ?>
        <?php else: ?>
            
            <!-- Fallback AI Content Template -->
            <div class="ai-section">
                <h3><i class="fas fa-chart-line"></i> Market Overview</h3>
                <p>Based on current market data analysis, <?php echo htmlspecialchars($property_address); ?> is positioned in a 
                <?php echo isset($market_trend) ? strtolower($market_trend) : 'stable'; ?> market segment. Recent comparable sales 
                indicate consistent demand in this price range and location.</p>
            </div>
            
            <div class="ai-section">
                <h3><i class="fas fa-home"></i> Property Positioning</h3>
                <p>This property demonstrates competitive positioning within its local market. Key factors contributing to its 
                market appeal include location accessibility, property condition, and neighborhood characteristics that align 
                with current buyer preferences.</p>
            </div>
            
            <div class="ai-section">
                <h3><i class="fas fa-lightbulb"></i> Key Insights</h3>
                <ul>
                    <li>Property features align with current market demand trends</li>
                    <li>Location provides good access to amenities and transportation</li>
                    <li>Comparable sales support current market positioning</li>
                    <li>Market conditions favor <?php echo isset($report_type) && $report_type === 'buyer' ? 'buyers' : 'sellers'; ?> in this segment</li>
                </ul>
            </div>
            
            <div class="ai-section">
                <h3><i class="fas fa-compass"></i> Market Recommendations</h3>
                <p>Consider market timing, local development plans, and seasonal trends when making decisions. 
                The current market environment provides opportunities for strategic positioning.</p>
            </div>
            
        <?php endif; ?>
    </div>
    
    <!-- AI Confidence Indicator -->
    <div class="ai-confidence">
        <div class="confidence-header">
            <i class="fas fa-gauge-high"></i>
            <span>Analysis Confidence</span>
        </div>
        <div class="confidence-bar">
            <div class="confidence-fill" style="width: 85%"></div>
        </div>
        <div class="confidence-text">
            High confidence based on comprehensive data analysis
        </div>
    </div>
    
    <!-- AI Disclaimer -->
    <div class="ai-disclaimer">
        <i class="fas fa-info-circle"></i>
        <span>This analysis is generated by AI based on available market data and should be used in conjunction with professional real estate advice.</span>
    </div>
    
</div>

<style>
.ai-insights {
    background: linear-gradient(135deg, var(--card-background), rgba(74, 222, 128, 0.02));
    border: 1px solid var(--border-light);
    border-radius: var(--radius-lg);
    padding: var(--spacing-xl);
    box-shadow: var(--shadow);
    margin-bottom: var(--spacing-xl);
    position: relative;
    overflow: hidden;
}

.ai-insights::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 4px;
    background: linear-gradient(90deg, var(--theme-color), #10b981, #06b6d4);
}

.ai-header {
    display: flex;
    align-items: center;
    gap: var(--spacing-md);
    margin-bottom: var(--spacing-xl);
    flex-wrap: wrap;
}

.ai-icon {
    width: 3.5rem;
    height: 3.5rem;
    background: linear-gradient(135deg, var(--theme-color), #10b981);
    color: white;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.5rem;
    flex-shrink: 0;
    animation: pulse 2s infinite;
}

@keyframes pulse {
    0% { transform: scale(1); }
    50% { transform: scale(1.05); }
    100% { transform: scale(1); }
}

.ai-title-section {
    flex: 1;
    min-width: 0;
}

.ai-title {
    margin: 0;
    font-size: var(--font-size-xl);
    font-weight: 700;
    color: var(--text-primary);
    background: linear-gradient(135deg, var(--theme-color), #10b981);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}

.ai-subtitle {
    margin: var(--spacing-xs) 0 0;
    color: var(--text-secondary);
    font-size: var(--font-size-sm);
    font-weight: 500;
}

.ai-badge {
    background: var(--theme-color-light);
    color: var(--theme-color);
    padding: var(--spacing-xs) var(--spacing-sm);
    border-radius: var(--radius-xl);
    font-size: var(--font-size-xs);
    font-weight: 600;
    display: flex;
    align-items: center;
    gap: var(--spacing-xs);
    white-space: nowrap;
}

.ai-content {
    line-height: 1.7;
    color: var(--text-primary);
}

.ai-content h3 {
    color: var(--theme-color);
    font-size: var(--font-size-lg);
    font-weight: 600;
    margin: var(--spacing-xl) 0 var(--spacing-md);
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
}

.ai-content h3:first-child {
    margin-top: 0;
}

.ai-content h3 i {
    color: var(--theme-color);
    font-size: 1.1rem;
}

.ai-content p {
    margin-bottom: var(--spacing-md);
    text-align: justify;
}

.ai-content ul, .ai-content ol {
    margin-bottom: var(--spacing-md);
    padding-left: var(--spacing-lg);
}

.ai-content li {
    margin-bottom: var(--spacing-xs);
    position: relative;
}

.ai-content ul li::marker {
    color: var(--theme-color);
}

.ai-section {
    background: rgba(255, 255, 255, 0.5);
    border: 1px solid var(--border-light);
    border-radius: var(--radius);
    padding: var(--spacing-lg);
    margin-bottom: var(--spacing-lg);
    transition: all var(--transition);
}

.ai-section:hover {
    transform: translateY(-2px);
    box-shadow: var(--shadow-lg);
    border-color: var(--theme-color);
}

.ai-confidence {
    background: var(--background);
    border: 1px solid var(--border-light);
    border-radius: var(--radius);
    padding: var(--spacing-lg);
    margin: var(--spacing-xl) 0 var(--spacing-lg);
}

.confidence-header {
    display: flex;
    align-items: center;
    gap: var(--spacing-sm);
    margin-bottom: var(--spacing-md);
    font-weight: 600;
    color: var(--text-primary);
}

.confidence-bar {
    width: 100%;
    height: 8px;
    background: var(--border-light);
    border-radius: 4px;
    overflow: hidden;
    margin-bottom: var(--spacing-sm);
}

.confidence-fill {
    height: 100%;
    background: linear-gradient(90deg, var(--theme-color), #10b981);
    border-radius: 4px;
    transition: width 2s ease-out;
}

.confidence-text {
    font-size: var(--font-size-sm);
    color: var(--text-secondary);
    text-align: center;
}

.ai-disclaimer {
    display: flex;
    align-items: flex-start;
    gap: var(--spacing-sm);
    background: rgba(59, 130, 246, 0.05);
    border: 1px solid rgba(59, 130, 246, 0.2);
    border-radius: var(--radius);
    padding: var(--spacing-md);
    font-size: var(--font-size-sm);
    color: var(--text-secondary);
    line-height: 1.5;
}

.ai-disclaimer i {
    color: #3b82f6;
    margin-top: 2px;
    flex-shrink: 0;
}

@media (max-width: 480px) {
    .ai-header {
        text-align: center;
        flex-direction: column;
        gap: var(--spacing-sm);
    }
    
    .ai-title-section {
        text-align: center;
    }
    
    .ai-content p {
        text-align: left;
    }
}

@media (prefers-reduced-motion: reduce) {
    .ai-icon {
        animation: none;
    }
    
    .confidence-fill {
        transition: none;
    }
}
</style>

<script>
// Animate confidence bar on load
document.addEventListener('DOMContentLoaded', function() {
    const confidenceFill = document.querySelector('.confidence-fill');
    if (confidenceFill) {
        // Reset width first
        confidenceFill.style.width = '0%';
        
        // Animate to target width after a short delay
        setTimeout(() => {
            confidenceFill.style.width = '85%';
        }, 500);
    }
    
    // Add click-to-expand functionality for AI sections
    const aiSections = document.querySelectorAll('.ai-section');
    aiSections.forEach(section => {
        section.addEventListener('click', function() {
            this.classList.toggle('expanded');
        });
    });
});

// Track AI insights interaction
if (window.mobileReport) {
    window.mobileReport.trackInteraction('ai_insights_viewed', {
        has_custom_content: <?php echo !empty($ai_content) ? 'true' : 'false'; ?>,
        property_address: '<?php echo htmlspecialchars($property_address); ?>'
    });
}
</script>