	<article class="section">
    <div class="container">
      <h1><b class="text-primary"> FAQ's</b> Frequently Asked Questions</h1>
         </div>
        </article>
	
    <div class="clearfix">
    </div>
    <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="site-comtent" id="primary">
                                <section class="section type2">
                                    <div class="subpage-title">
                                        <h5>Frequently Asked Questions</h5>
                                    </div>
                                    <div class="panel-group" role="tablist" aria-multiselectable="true">
                                        <div class="panel panel-default">
                                            <div class="panel-heading" role="tab" id="heading1">
                                                <h4 class="panel-title">
                                                    <a href="#collapse1" data-toggle="collapse" class="accordion-toggle collapsed" role="button" aria-expanded="false" aria-controls="collapse1">
                                                   What Format Do They Flyers Come In?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse1" role="tabpanel" aria-labelledby="heading1">
                                                <div class="panel-body">
                                                   All flyers are in PDF format. In the near future we will be adding the ability to export in other formats.
                                                </div>
                                            </div>
                                        </div>
                                        <div class="panel panel-default">
                                            <div class="panel-heading" role="tab" id="heading2">
                                                <h4 class="panel-title">
                                                    <a href="#collapse2" data-toggle="collapse" class="accordion-toggle collapsed" role="button" aria-expanded="false" aria-controls="collapse2">
                                                   Are the Images High Resolution?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse2" role="tabpanel" aria-labelledby="heading2">
                                                <div class="panel-body">
                                                   Yes. All of our images are high resolution to allow for the best printing possible.
                                                </div>
                                            </div>
                                        </div>
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse3" data-toggle="collapse" class="accordion-toggle collapsed">
                                                   Is the flyer print ready?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse3">
                                                <div class="panel-body">
                                                    Yes. All the flyers generated by listing-pitch.com are print ready.
                                                </div>
                                            </div>
                                        </div>
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse4" data-toggle="collapse" class="accordion-toggle collapsed">
                                                    Can I edit after finalizing?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse4">
                                                <div class="panel-body">
                                                    After a flyer has been finalized it cannot be edited. We have included a recreate button that automatically recreates the flyer and places it in to our editor. From here you can make the necessary changes and finalize it.
                                                </div>
                                            </div>
                                        </div>
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                   Can I save a flyer?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                     Yes. You can save a flyer that you are working on. You can come back to it at a different date and finalize it.
                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                   Can I order printing?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                   Yes we give our users the ability to order high quality color copies directly from us.
                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                  How do I get my printed flyers?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                    After printing we ship them to you in one of our cool colorful envelopes.
                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                   How long does it take to receive printed flyers?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                   If you order printing before our 4pm cut-off time, you will receive your flyers the next day before 5pm.
                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                   Does it cost anything to sign up?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                   No. You can sign up for free.
                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                   How much is each flyer?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                    You have two options: <br/>
													<strong>1)Pay-As-You-Go</strong> - This options allows you to purchase a single flyer at $2<br/>
													<strong>2)Buy Credits (Best Bargin)</strong> – This feature allows you to buy credits. Each flyer will cost you 1 credit. So $5 = 5 Credits.

                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                  How many credits can I buy?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                    We allow you to buy 5 credits at a time If you run out, you can always buy more credits at any time. 
                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                  What are credits?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                   Credits are a way to prepay for flyers that you will eventually create. Each credit allows you to personalize 1 flyer.  So $5 = 5 Credits = 5 PDF flyers.
                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                  Do my credits expire?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                   Credits do not expire. 
                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                   Are there training videos?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                   Yes we have training videos that show you how to navigate around our website as well as use our online designer.
                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                  What can I add to a flyer?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                    You can add the following:<br/>
													Your picture, a team members or picture, or both your pictures.<br/>
													Your contact info, your team members contact info, or both of your info.<br/>
													Your company logo

                                                </div>
                                            </div>
                                        </div>
										 <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a href="#collapse5" data-toggle="collapse" class="accordion-toggle collapsed">
                                                  Is there a contract or cancelation fee?
                                                    </a>
                                                </h4>
                                            </div>
                                            <div class="panel-collapse collapse" id="collapse5">
                                                <div class="panel-body">
                                                    There is no contracts or cancelation fee.
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>
                            </div>
                        </div>
                    </div>
    </div>
    <div class="clearfix">
    </div>