<?php
defined('BASEPATH') OR exit('No direct script access allowed');

// FAQ data array for better maintainability
$faq_items = array(
    array(
        'id' => 'formats',
        'question' => 'What Format Do They Flyers Come In?',
        'answer' => 'All flyers are in PDF format. In the near future we will be adding the ability to export in other formats.'
    ),
    array(
        'id' => 'resolution',
        'question' => 'Are the Images High Resolution?',
        'answer' => 'Yes. All of our images are high resolution to allow for the best printing possible.'
    ),
    array(
        'id' => 'print-ready',
        'question' => 'Is the flyer print ready?',
        'answer' => 'Yes. All the flyers generated by listing-pitch.com are print ready.'
    ),
    array(
        'id' => 'edit-finalized',
        'question' => 'Can I edit after finalizing?',
        'answer' => 'After a flyer has been finalized it cannot be edited. We have included a recreate button that automatically recreates the flyer and places it in to our editor. From here you can make the necessary changes and finalize it.'
    ),
    array(
        'id' => 'save-flyer',
        'question' => 'Can I save a flyer?',
        'answer' => 'Yes. You can save a flyer that you are working on. You can come back to it at a different date and finalize it.'
    ),
    array(
        'id' => 'order-printing',
        'question' => 'Can I order printing?',
        'answer' => 'Yes we give our users the ability to order high quality color copies directly from us.'
    ),
    array(
        'id' => 'delivery',
        'question' => 'How do I get my printed flyers?',
        'answer' => 'After printing we ship them to you in one of our cool colorful envelopes.'
    ),
    array(
        'id' => 'delivery-time',
        'question' => 'How long does it take to receive printed flyers?',
        'answer' => 'If you order printing before our 4pm cut-off time, you will receive your flyers the next day before 5pm.'
    ),
    array(
        'id' => 'signup-cost',
        'question' => 'Does it cost anything to sign up?',
        'answer' => 'No. You can sign up for free.'
    ),
    array(
        'id' => 'pricing',
        'question' => 'How much is each flyer?',
        'answer' => 'You have two options:<br/><strong>1) Pay-As-You-Go</strong> - This option allows you to purchase a single flyer at $2<br/><strong>2) Buy Credits (Best Bargain)</strong> – This feature allows you to buy credits. Each flyer will cost you 1 credit. So $5 = 5 Credits.'
    ),
    array(
        'id' => 'credit-limit',
        'question' => 'How many credits can I buy?',
        'answer' => 'We allow you to buy 5 credits at a time. If you run out, you can always buy more credits at any time.'
    ),
    array(
        'id' => 'what-credits',
        'question' => 'What are credits?',
        'answer' => 'Credits are a way to prepay for flyers that you will eventually create. Each credit allows you to personalize 1 flyer. So $5 = 5 Credits = 5 PDF flyers.'
    ),
    array(
        'id' => 'credit-expiry',
        'question' => 'Do my credits expire?',
        'answer' => 'Credits do not expire.'
    ),
    array(
        'id' => 'training',
        'question' => 'Are there training videos?',
        'answer' => 'Yes we have training videos that show you how to navigate around our website as well as use our online designer.'
    ),
    array(
        'id' => 'customization',
        'question' => 'What can I add to a flyer?',
        'answer' => 'You can add the following:<br/>Your picture, a team member\'s picture, or both your pictures.<br/>Your contact info, your team member\'s contact info, or both of your info.<br/>Your company logo'
    ),
    array(
        'id' => 'contract',
        'question' => 'Is there a contract or cancelation fee?',
        'answer' => 'There is no contract or cancelation fee.'
    )
);

// Template data for base template
$template_data = array(
    'title' => 'Frequently Asked Questions',
    'meta_description' => 'Find answers to frequently asked questions about Modern Agent real estate flyers, pricing, printing, and features.',
    'meta_keywords' => 'FAQ, real estate flyers, questions, pricing, printing, Modern Agent',
    'additional_css' => array(),
    'additional_js' => array()
);

// Capture the FAQ content
ob_start();
?>

<!-- FAQ Page Header -->
<header class="page-hero" role="banner">
    <div class="container">
        <div class="hero-content">
            <h1 class="hero-title">
                <span class="text-primary">FAQ's</span> 
                <span class="hero-subtitle">Frequently Asked Questions</span>
            </h1>
            <p class="hero-description">Find answers to common questions about our real estate flyer service</p>
        </div>
    </div>
</header>

<!-- Main Content -->
<main class="main-content" role="main">
    <div class="container">
        <div class="content-grid">
            <!-- FAQ Section -->
            <section class="faq-section" aria-labelledby="faq-heading">
                <div class="section-header">
                    <h2 id="faq-heading" class="section-title">Frequently Asked Questions</h2>
                    <p class="section-description">Get quick answers to the most common questions about our service</p>
                </div>

                <!-- FAQ Accordion -->
                <div class="accordion" role="tablist" aria-label="Frequently Asked Questions">
                    <?php foreach ($faq_items as $index => $faq): ?>
                    <div class="accordion-item">
                        <h3 class="accordion-header">
                            <button type="button" 
                                    class="accordion-button"
                                    id="faq-button-<?php echo htmlspecialchars($faq['id'], ENT_QUOTES, 'UTF-8'); ?>"
                                    aria-expanded="false"
                                    aria-controls="faq-content-<?php echo htmlspecialchars($faq['id'], ENT_QUOTES, 'UTF-8'); ?>"
                                    role="tab">
                                <span class="accordion-question">
                                    <?php echo htmlspecialchars($faq['question'], ENT_QUOTES, 'UTF-8'); ?>
                                </span>
                                <span class="accordion-icon" aria-hidden="true">
                                    <i class="fa fa-chevron-down"></i>
                                </span>
                            </button>
                        </h3>
                        <div class="accordion-body"
                             id="faq-content-<?php echo htmlspecialchars($faq['id'], ENT_QUOTES, 'UTF-8'); ?>"
                             role="tabpanel"
                             aria-labelledby="faq-button-<?php echo htmlspecialchars($faq['id'], ENT_QUOTES, 'UTF-8'); ?>"
                             aria-hidden="true">
                            <div class="accordion-content">
                                <?php echo $faq['answer']; // This is intentionally not escaped as it contains HTML ?>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </section>

            <!-- Sidebar with Quick Links -->
            <aside class="sidebar" role="complementary" aria-label="Quick links">
                <div class="sidebar-section">
                    <h3 class="sidebar-title">Quick Links</h3>
                    <nav class="sidebar-nav" role="navigation" aria-label="Quick navigation">
                        <ul class="sidebar-menu">
                            <li><a href="<?php echo site_url('register'); ?>" class="sidebar-link">Sign Up Free</a></li>
                            <li><a href="<?php echo site_url('pricing'); ?>" class="sidebar-link">View Pricing</a></li>
                            <li><a href="<?php echo site_url('howto'); ?>" class="sidebar-link">How It Works</a></li>
                            <li><a href="<?php echo site_url('contact'); ?>" class="sidebar-link">Contact Support</a></li>
                        </ul>
                    </nav>
                </div>

                <div class="sidebar-section">
                    <h3 class="sidebar-title">Popular Topics</h3>
                    <nav class="topic-nav" role="navigation" aria-label="Popular FAQ topics">
                        <ul class="topic-list">
                            <li><a href="#faq-content-pricing" class="topic-link">Pricing & Credits</a></li>
                            <li><a href="#faq-content-print-ready" class="topic-link">Print Quality</a></li>
                            <li><a href="#faq-content-delivery" class="topic-link">Delivery Options</a></li>
                            <li><a href="#faq-content-customization" class="topic-link">Customization</a></li>
                        </ul>
                    </nav>
                </div>

                <div class="sidebar-section cta-section">
                    <h3 class="cta-title">Still Have Questions?</h3>
                    <p class="cta-text">Can't find what you're looking for? Our support team is here to help.</p>
                    <a href="<?php echo site_url('contact'); ?>" class="btn btn-primary btn-block">
                        <i class="fa fa-envelope" aria-hidden="true"></i>
                        Contact Support
                    </a>
                </div>
            </aside>
        </div>
    </div>
</main>

<?php
$template_data['content'] = ob_get_clean();

// Add inline JavaScript for FAQ functionality
$template_data['inline_js'] = '
// FAQ Accordion functionality
(function() {
    "use strict";
    
    const FAQAccordion = {
        init: function() {
            this.bindEvents();
            this.setupKeyboardNavigation();
        },
        
        bindEvents: function() {
            // Accordion toggle
            document.addEventListener("click", function(e) {
                if (e.target.closest(".accordion-button")) {
                    e.preventDefault();
                    const button = e.target.closest(".accordion-button");
                    FAQAccordion.toggleAccordion(button);
                }
            });
            
            // Topic navigation
            document.addEventListener("click", function(e) {
                if (e.target.closest(".topic-link")) {
                    e.preventDefault();
                    const link = e.target.closest(".topic-link");
                    const targetId = link.getAttribute("href").substring(1);
                    FAQAccordion.openAccordionById(targetId);
                }
            });
        },
        
        setupKeyboardNavigation: function() {
            document.addEventListener("keydown", function(e) {
                if (e.target.classList.contains("accordion-button")) {
                    if (e.key === "Enter" || e.key === " ") {
                        e.preventDefault();
                        FAQAccordion.toggleAccordion(e.target);
                    } else if (e.key === "ArrowDown" || e.key === "ArrowUp") {
                        e.preventDefault();
                        FAQAccordion.navigateAccordion(e.target, e.key === "ArrowDown");
                    }
                }
            });
        },
        
        toggleAccordion: function(button) {
            const content = document.getElementById(button.getAttribute("aria-controls"));
            const isExpanded = button.getAttribute("aria-expanded") === "true";
            const icon = button.querySelector(".accordion-icon i");
            
            // Close other accordions (optional - remove for multiple open)
            this.closeOtherAccordions(button);
            
            // Toggle current accordion
            button.setAttribute("aria-expanded", !isExpanded);
            content.setAttribute("aria-hidden", isExpanded);
            
            if (isExpanded) {
                content.classList.remove("show");
                icon.className = "fa fa-chevron-down";
            } else {
                content.classList.add("show");
                icon.className = "fa fa-chevron-up";
                
                // Smooth scroll to accordion if needed
                setTimeout(() => {
                    button.scrollIntoView({ behavior: "smooth", block: "nearest" });
                }, 100);
            }
        },
        
        closeOtherAccordions: function(currentButton) {
            const allButtons = document.querySelectorAll(".accordion-button");
            allButtons.forEach(button => {
                if (button !== currentButton && button.getAttribute("aria-expanded") === "true") {
                    const content = document.getElementById(button.getAttribute("aria-controls"));
                    const icon = button.querySelector(".accordion-icon i");
                    
                    button.setAttribute("aria-expanded", "false");
                    content.setAttribute("aria-hidden", "true");
                    content.classList.remove("show");
                    icon.className = "fa fa-chevron-down";
                }
            });
        },
        
        openAccordionById: function(contentId) {
            const content = document.getElementById(contentId);
            if (content) {
                const button = document.querySelector(`[aria-controls="${contentId}"]`);
                if (button && button.getAttribute("aria-expanded") !== "true") {
                    this.toggleAccordion(button);
                }
                
                // Scroll to the accordion
                setTimeout(() => {
                    content.scrollIntoView({ behavior: "smooth", block: "start" });
                }, 200);
            }
        },
        
        navigateAccordion: function(currentButton, isDown) {
            const allButtons = Array.from(document.querySelectorAll(".accordion-button"));
            const currentIndex = allButtons.indexOf(currentButton);
            let targetIndex;
            
            if (isDown) {
                targetIndex = currentIndex < allButtons.length - 1 ? currentIndex + 1 : 0;
            } else {
                targetIndex = currentIndex > 0 ? currentIndex - 1 : allButtons.length - 1;
            }
            
            allButtons[targetIndex].focus();
        }
    };
    
    // Initialize when DOM is ready
    document.addEventListener("DOMContentLoaded", function() {
        FAQAccordion.init();
    });
    
    // Expose for manual use
    window.FAQAccordion = FAQAccordion;
})();
';

// Load the base template
$this->load->view('templates/base', $template_data);
?>