<?php if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|    http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
 */
if (php_sapi_name() !== 'cli') {
    if ($_SERVER['SERVER_PORT'] == 443) {
        $protocal = 'https://';
    } else {
        $protocal = 'http://';

        $pageURL = 'http';
        // if ($_SERVER["HTTPS"] == "on") {$pageURL .= "s";}
        $pageURL .= "://";
        // if ($_SERVER["SERVER_PORT"] != "80") {
        // $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];
        // } else {
        $pageURL .= $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
        // }

        $uri = str_replace("http://", "https://", $pageURL);
        // header('Location: '.$uri);
    }
} else {
    $protocal = 'http://';
}
//$config['base_url']    = $protocal.'beta.mylistingpitch.com/beta/';
//$config['base_url']    = $protocal.'localhost/dev_listingpitch/';
//$config['base_url']    = $protocal.'modernagent.io/';
// $config['base_url']     = '';
$config['base_url'] = $protocal . $_SERVER['HTTP_HOST'] . '/';
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
 */
$config['index_page'] = 'index.php';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'            Default - auto detects
| 'PATH_INFO'        Uses the PATH_INFO
| 'QUERY_STRING'    Uses the QUERY_STRING
| 'REQUEST_URI'        Uses the REQUEST_URI
| 'ORIG_PATH_INFO'    Uses the ORIG_PATH_INFO
|
 */
$config['uri_protocol'] = 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
 */

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
 */
$config['language'] = 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
 */
$config['log_threshold'] = 4;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
 */
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
 */
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
 */
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
 */
$config['encryption_key'] = 'rC0qaRzZ7V5AqdeJGqZwOLjV6j4V7hOt';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'        = the name you want for the cookie
| 'sess_expiration'            = the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'    = Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'        = Whether to encrypt the cookie
| 'sess_use_database'        = Whether to save the session data to a database
| 'sess_table_name'            = The name of the session database table
| 'sess_match_ip'            = Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'    = Whether to match the User Agent when reading the session data
| 'sess_time_to_update'        = how many seconds between CI refreshing Session Information
|
 */
$config['sess_cookie_name'] = 'ci_session';
$config['sess_expiration'] = 7200;
$config['sess_expire_on_close'] = false;
$config['sess_encrypt_cookie'] = false;
// $config['sess_use_database']    = TRUE;
$config['sess_use_database'] = true;
$config['sess_table_name'] = 'ci_sessions';
$config['sess_match_ip'] = true;
$config['sess_match_useragent'] = false;
$config['sess_time_to_update'] = 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
 */
$config['cookie_prefix'] = "ma_";
$config['cookie_domain'] = !empty($_ENV['MAIN_DOMAIN']) ? '.' . $_ENV['MAIN_DOMAIN'] : "";
// if(defined('CI_REQUEST') && CI_REQUEST == 'external'){
// }
// else {
//     $config['cookie_path']        = "/";
// }
$useragent = isset($_SERVER['HTTP_USER_AGENT']) ? $_SERVER['HTTP_USER_AGENT'] : '';
$config['cookie_path'] = "/; SameSite=None";
if (strpos($useragent, "Macintosh; Intel Mac OS X 10_14") !== false) {
    // regular safari
    if (strpos($useragent, "Version/") !== false && strpos($useragent, "Safari") !== false) {
        $config['cookie_path'] = "/";
    } elseif (preg_match('|AppleWebKit/[\.\d]+ \(KHTML, like Gecko\)$|', $useragent)) {
        $config['cookie_path'] = "/";
    }
}
if (isset($_SERVER['HTTP_USER_AGENT']) && strpos($_SERVER['HTTP_USER_AGENT'], 'Safari') && !strpos($_SERVER['HTTP_USER_AGENT'], 'Chrome')) {
    $config['cookie_domain'] = "";
}
$config['cookie_secure'] = true;
/*
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
 */
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
 */
$config['enable_hooks'] = true;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
 */
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
 */
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
 */
$config['allow_get_array'] = true;
$config['enable_query_strings'] = false;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|    0 = Disables logging, Error logging TURNED OFF
|    1 = Error Messages (including PHP errors)
|    2 = Debug Messages
|    3 = Informational Messages
|    4 = All Messages
$config['cookie_httponly']  = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
 */
$config['global_xss_filtering'] = false;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
 */
$config['csrf_protection'] = false;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
 */
$config['compress_output'] = false;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
 */
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
 */
$config['rewrite_short_tags'] = false;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
 */
$config['proxy_ips'] = '';
$config['wkhtmltopdf_path'] = '/usr/local/bin/wkhtmltopdf';
$config['wkhtmltopdf_zoom'] = 1.285;
$config['wkhtmltopdf_zoom_seller'] = 0.7999;
$config['qpdf_path'] = 'qpdf';

$config['seller_report_title'] = array(
    1 => array(
        1 => 'Sellers Report',
        2 => 'Contents',
        3 => 'Areal View',
        4 => 'Prospective Property',
        5 => 'Area Sales Analysis',
        6 => 'Sales comparables',
        8 => 'Rang of Sales',
        9 => 'Home buying Process',
        10 => 'How buyers find home',
        11 => 'Pricing Correctly',
        12 => 'Average Days on Market',
        13 => 'Pics & Online Exposure',
        14 => 'Printed Collateral',
        15 => 'Social Media & Networking',
        16 => 'Analyze & Optimize',
        17 => 'Negotiating Offers',
        18 => 'Typical Transaction',
        19 => 'Promise To Client',
    ),
    2 => array(
        1 => 'Sellers Report',
        2 => 'Owner',
        5 => 'Areal View',
        6 => 'Prospective Property',
        7 => 'Area Sales Analysis',
        8 => 'Rang of Sales',
        9 => 'Checklist',
        10 => 'Sales comparables',
        12 => 'Qualified Agents',
        13 => 'Pricing your homes',
        14 => 'Pricing Correctly',
        15 => 'Days on Market',
        16 => 'Analyze & Optimize',
        17 => 'Selling Plan',
        18 => 'Print Advertising',
        19 => 'Marketing',
        21 => 'Agent',
        22 => 'Promise',
        23 => 'Thank You',
        24 => 'Final',
    ),
    3 => array(
        1 => 'Sellers Report',
        4 => 'Our Mission',
        5 => 'Accolades',
        6 => 'Aerial View',
        7 => 'Prospective Property',
        8 => 'Area Sales Analysis',
        9 => 'Sales comparables',
        11 => 'Range of Sales',
        12 => 'Pricing Correctly',
        13 => 'Days on Market',
        14 => 'Digital Marketing Plan',
        15 => 'Social Proof',
        16 => 'Sales Road-map',
        18 => 'Analyze Optimize',
        19 => 'Promise to Client',
        20 => 'Address',
    ),
);

$config['sqft'] = array(
    "0.20" => '0.20 +/-',
    "0.30" => '0.30 +/-',
    "0.40" => '0.40 +/-',
    "0.50" => '0.50 +/-',
    "0.60" => '0.60 +/-',
    "0.70" => '0.70 +/-',
    "0.80" => '0.80 +/-',
    "0.90" => '0.90 +/-',
    "1.00" => '1.00 +/-',
);

$config['radius_adjustment'] = array(
    "0.25" => '0.25 mi',
    "0.50" => '0.50 mi',
    "0.75" => '0.75 mi',
    "1.00" => '1.00 mi',
    "1.25" => '1.25 mi',
    "1.50" => '1.50 mi',
    "1.75" => '1.75 mi',
    "2.00" => '2.00 mi',
);

/* End of file config.php */
/* Location: ./application/config/config.php */
